######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 9 22:13:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += geotagwindow.h
SOURCES += geotagwindow.cpp main.cpp
